[package]
name = "glucosense-server"
version = "0.0.1"
authors = ["Johan Larsson <johan.larsson1989@gmail.com>"]

[dependencies]
tensorflow = "0.9.0"
postgres = "0.15.2"
diesel = "1.2.2"
futures = "0.2.1"
hyper = "0.11.26"
rayon = "1.0.1"
actix-web = "0.6"
